#!/usr/bin/python3

#lets use python3 in vim

import os
import subprocess
import requests
import json

def python_version():
    cmd = "python3 --version"
    output = subprocess.check_output(cmd, shell=True)
    print("Using python version: ", output.decode("utf-8").strip())


def github_api_request(owner, repo, cmd):
    url_request = "https://api.github.com/repos/" + owner + "/" + repo + "/" + cmd
    print("request url is: " + url_request)

    response = requests.get(url_request)
    print("url response code: " + str(response.status_code))
    print(response.text)

    response_json_list = json.loads(response.text)
    response_dict = {}
    response_dict = {index: value for index, value in enumerate(response_json_list)}

    return response_dict


if __name__ == "__main__":
    python_version()
    response_json_list = github_api_request("octocat", "Hello-World", "branches")
 
    response_dict = {index: value for index, value in enumerate(response_json_list)}



    print("data type is: " + str(type(response_dict)) )
    print("display keys in dictionary: " + str(response_dict.keys()))
  
    print("display dictory values by index keys\n")
    for x in range(len(response_dict)):
        print(response_dict[x])
